name: DockerHub Pushes

on: [push]


jobs:
   build:
     runs-on: ubuntu-latest
     steps: 

      - name: checkout code 
        uses: actions/checkout@v3

      - name: docker build & push action
        uses: mr-smithers-excellent/docker-build-push@v6.8
        with:
          image: ishaqmo/task2-validation
          tags: v1, latest
          registry: Docker.io
          dockerfile: Dockerfile
          username:  ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
