name: re-buildung

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v2

    - name: docker simulation
      uses: mr-smithers-excellent/docker-build-push@v6.8
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_TOKENS }} 

