name: Coderco

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Coderco
      uses: actions/checkout@v2
    - name: We are testing this version
      run: echo hello
    
    - name: use secret 
      run: echo the secret is "new secret"

    - name: Checkoutv2
      uses: actions/checkout@v4