name: Ishaq

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]



    steps:
     - name: 
       uses: actions/checkout@v3

     - name: set up python 
       uses: actions/setup-python@v3
       with: 
        python-version: ${{ matrix.python-version }}
    
    
     - name: install depencies
       run: |
         cd chapter4
         python -m pip install --upgrade pip 
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


     - name: run tests 
       run: |
        cd chapter4
        python -m. unittest discover 

     - name: notify us of success 
       run: echo "The Test passed on python ${{ matrix.python-version }}"
       if: success()

    

    



        


